# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

sudo: no
language: python
python: 2.7

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_cache"
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=tests

cache:
  directories:
    - pip_cache

script: bin/travis/test_dispatch.sh $TEST_SUITE
