---
# define volumes in docker-compose.override.yml so that can be ignored in CI
services:
  base:
    volumes:
      - .:/app
      - /app/.venv
  web:
    volumes:
      - .:/app
      - /app/.venv
  test:
    volumes:
      - .:/app
      - /app/.venv
  crash-ping-submitter:
    volumes:
      - ./crash_ping_submitter:/app
      - /app/.venv
