FROM python:3.11.2-alpine3.16@sha256:cb6c704d0d1f386a5c427a9ebd6fcce3978046b97c7caabf568e4dc241aafe1a

ARG groupid=5000
ARG userid=5000

WORKDIR /app/

RUN addgroup -g $groupid app && \
    adduser --disabled-password --gecos "" --home /home/app --ingroup app --uid $userid app && \
    chown app:app /app/

RUN apk add --no-cache tini

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN pip install -U 'pip>=20' && \
    pip install --no-cache-dir 'kent==1.0.0'

USER app

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/kent-server"]
CMD ["run"]
