# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:557.0.0-emulators@sha256:0b00e2892029c9e2bca3998d3914e2be45be0394df16b1b4efa859ad8761090b
# also available as google/cloud-sdk:<version>-emulators
