# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:563.0.0-emulators@sha256:6047b558760023909c3050d5e89c19aa0f64e288f7a3112b5cb536fa42149244
# also available as google/cloud-sdk:<version>-emulators
