# Define this image outside of docker-compose.yml so that it gets dependabot updates
FROM gcr.io/google.com/cloudsdktool/google-cloud-cli:463.0.0-emulators@sha256:4a3ef96d0379a5bf94285e743902a4d7da7f191aac6a542464e096bc72585eaa
# also available as google/cloud-sdk:<version>-emulators
